name: Update Key

on:
  schedule:
    - cron: "0 0 * * *" # Chạy mỗi ngày vào 00:00 UTC

jobs:
  update-key:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install requests library
      run: python -m pip install requests

    - name: Run Key Updater Script
      env:
        YOUR_GITHUB_ACCESS_TOKEN: ${{ secrets.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 }}
      run: |
        python script.py
