name: Update Key Daily

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update-key:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Python dependencies
      run: pip install requests

    - name: Generate and update key
      run: python update_key.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add HappyHubKey.txt
        git commit -m "Update key automatically"
        git push
